common/changes/@itwin/imodel-browser-react/raplemie-removeThumbnailCache_2021-08-04-14-26.json, packages/modules/imodel-browser/src/containers/iModelThumbnail/useIModelThumbnail.ts
Removed the local caching of iModel thumbnails, this will address an issue where the thumbnail can now be edited by create-imodel package and these changes werent reflected by the browser. It was also an issue if the thumbnails were edited anywhere else actually, so I removed this caching and will let the network handle the caching itself.
=> Remove iModelGrid thumbnail cache

common/changes/@itwin/create-imodel-react/raplemie-readmefixes_2021-08-04-15-46.json, common/changes/@itwin/delete-imodel-react/raplemie-readmefixes_2021-08-04-15-46.json, common/changes/@itwin/imodel-browser-react/raplemie-readmefixes_2021-08-04-15-46.json, common/changes/@itwin/manage-versions-react/raplemie-readmefixes_2021-08-04-15-46.json, packages/modules/create-imodel/README.md, packages/modules/delete-imodel/README.md, packages/modules/imodel-browser/README.md, packages/modules/manage-versions/README.md, packages/modules/manage-versions/package.json
README.md "Changelog" link are pointing to ./Changelog.md, which do not work correctly when displayed in npm.
=> Fix READMEs when displayed in npm

common/changes/@itwin/imodel-browser-react/raplemie-postProcessCallback_2021-08-09-19-01.json, packages/apps/storybook/src/imodel-browser/IModelGrid.stories.tsx, packages/apps/storybook/src/imodel-browser/ProjectGrid.stories.tsx, packages/modules/imodel-browser/src/containers/ProjectGrid/ProjectGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx
Adding `postProcessCallback` prop to the 2 grids component, this will allow users to take action on the fetched data, allowing modification (sorting, adding or deleting elements) without us having to handle these, allowing us on focusing on the REST API's features only.
=> post process callbacks

common/changes/@itwin/create-imodel-react/vilius-content-type_2021-08-10-10-55.json, packages/modules/create-imodel/src/components/create-imodel/CreateIModel.test.tsx, packages/modules/create-imodel/src/components/create-imodel/CreateIModel.tsx, packages/modules/create-imodel/src/components/update-imodel/UpdateIModel.test.tsx, packages/modules/create-imodel/src/components/update-imodel/UpdateIModel.tsx
iModel Hub in APIM is planning to validate Content-Type headers. So added it in places where it was missing.
=> Added Content-Type header to POST and PATCH requests

common/changes/@itwin/manage-versions-react/vilius-tab-enum-fix_2021-08-11-05-37.json, packages/modules/manage-versions/src/index.ts
=> Moved `ManageVersionsTabs` to regular exports so it could be used when setting `currentTab`.

common/changes/@itwin/imodel-browser-react/raplemie-fixMorePageWithDataOverrides_2022-06-02-16-34.json, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.test.ts, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts
When the `data` is provided by the user using the `apiOverrides`, we are still showing the trailing cards for the "fetch more", however these are never correctly removed.
So whenever we have this type of data provided, we now disable that paging mechanism. (A further enhancement could be to allow that paging to happen with this data, however now that https://www.npmjs.com/package/@itwin/itwinui-layouts-react exists and provide a grid itself, I'm not sure it is worth adding features to this aspect of the IModelGrid.
=> Remove page management if data is provided.

common/changes/@itwin/manage-versions-react/changedFilesColumn_2023-02-21-12-05.json, packages/modules/manage-versions/src/components/ManageVersions/ChangesTab/ChangesTab.test.tsx, packages/modules/manage-versions/src/components/ManageVersions/ChangesTab/ChangesTab.tsx, packages/modules/manage-versions/src/components/ManageVersions/ManageVersions.test.tsx, packages/modules/manage-versions/src/components/ManageVersions/ManageVersions.tsx, packages/modules/manage-versions/src/components/ManageVersions/types.ts, packages/modules/manage-versions/src/mocks.ts, packages/modules/manage-versions/src/models/changeset.ts
Added an optional boolean prop "shouldShowChangedFiles" to ManageVersion component. With the use of this flag consumer app can decide whether to show changed files columns in changes tab table or not.
=> Added Changed Files column to the changes tab table

packages/apps/storybook/src/addon/register.js
Since the oidc scopes are changed to use iTwins, the storybook addon will now use the iTwins API rather than the previous Projects one, it will still only require "Project" subclass.
=> Storybook Addon: Use `itwins` API since the scopes were changed.

packages/modules/imodel-browser/src/components/gridStructure/GridStructure.scss
Addition of `ThemeProvider` around the `IModelTile` and `ITwinTile` components cause the tiles to have different height when the descriptions are different, this fixes it by expanding the grid content (`ThemeProviders`) to the full available height of the grid element.
Before: 
After:
=> Fix Tile height issue introduced by ThemeProvider

common/changes/@itwin/imodel-browser-react/DanishM-limit_2023-08-30-09-47.json, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.test.ts, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts
Added the ability to limit the page size of iModel tiles.
=> Ability to limit iModel tiles

common/changes/@itwin/manage-versions-react/sourabh-context-menu-update-for-manage-versions_2024-03-28-13-32.json, packages/modules/manage-versions/src/clients/changesetClient.test.ts, packages/modules/manage-versions/src/clients/changesetClient.ts, packages/modules/manage-versions/src/components/ManageVersions/ManageVersions.test.tsx, packages/modules/manage-versions/src/components/ManageVersions/ManageVersions.tsx, packages/modules/manage-versions/src/components/ManageVersions/VersionsTab/VersionsTab.test.tsx, packages/modules/manage-versions/src/components/ManageVersions/VersionsTab/VersionsTab.tsx, packages/modules/manage-versions/src/components/ManageVersions/types.ts, packages/modules/manage-versions/src/components/contextMenu/ContextMenu.test.tsx, packages/modules/manage-versions/src/components/contextMenu/ContextMenu.tsx, packages/modules/manage-versions/src/models/checkpoint.ts, packages/modules/manage-versions/src/models/index.ts
**Changes: -**
_**Added**_
- **Download Named Version**: Users can now directly download the associated files of a Named Version from the UI. This enhancement simplifies the process of obtaining version-specific data, improving the user workflow. Simply click on the new download icon next to the version you wish to download.
- **Context Menu in Named Versions**: A context menu has been introduced to provide quick access to multiple actions for each Named Version. This new feature allows users to perform actions such as updating version details, downloading version data, and more, in a single, convenient location.
- **Checkpoint API Method**:  Added a new `getChangesetCheckpoint` method that downloads `.bim` files for named version that has changes up to a certain Changeset. For more …
=> Adding Download action for named version.

common/changes/@itwin/imodel-browser-react/john-access-token-prop_2024-09-13-17-50.json, packages/apps/storybook/src/imodel-browser/IModelGrid.stories.tsx, packages/apps/storybook/src/imodel-browser/ITwinGrid.stories.tsx, packages/apps/storybook/src/utils/storyHelp.ts, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinData.ts, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts, packages/modules/imodel-browser/src/containers/iModelThumbnail/IModelThumbnail.tsx, packages/modules/imodel-browser/src/containers/iModelThumbnail/useIModelThumbnail.ts, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.tsx
Closes AB#1518319
Closes https://github.com/iTwin/admin-components-react/issues/124
ITwinGrid and IModelGrid take a constant `accessToken` string as a prop. But the `accessToken` will eventually expire. So it would be better to accept a function `() => Promise<string>` as a prop, so that whenever the access token is used, it can be checked for expiry and renewed.
Works in Storybook and manually tested with an app I have, looks okay to me.
Note: I couldn't get storybook working at first... it was because the scopes for new OIDC clients have changed to `itwin-platform`. Let me know if you want me to make that change in `.storybook/preview.js`
=> Access token can be a function

common/changes/@itwin/imodel-browser-react/fix-list-truncated_2024-10-22-00-22.json, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts
When scrolling to the bottom of the list, onBottomReached function is being called indefinitely and no results are being returned when trying to fetch the full list.
Before Fix
After Fix
=> fix list not loading more data

common/changes/@itwin/imodel-browser-react/fix-imodel-sorting_2024-10-18-19-49.json, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelSort.test.ts, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelTableConfig.tsx, packages/modules/imodel-browser/src/types.ts
When providing a sortOptions and changing the descending option from true to false, the iModels in the grid or list do not get sorted accordingly.
Before Fix
After Fix
=> Refactor IModelGrid component to handle sort options dynamically

common/changes/@itwin/imodel-browser-react/itwin-favorites_2024-11-21-19-36.json, packages/apps/storybook/.storybook/preview.js, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinTile.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinFavorites.ts
Added favorite/unfavorite functionality to iTwin grid directly.
=> Add favorites functionality to ITwinGrid and ITwinTile components

common/changes/@itwin/imodel-browser-react/hide-empty-dropdown-table_2024-12-03-16-27.json, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinTableConfig.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelTableConfig.tsx
=> Hide actions dropdown in iTwin/iModel browser when no actions are defined

common/changes/@itwin/imodel-browser-react/fix-itwin-favorites_2024-11-22-02-01.json, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinTile.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinData.ts, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinFavorites.test.ts, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinFavorites.ts, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinTableConfig.tsx
Fix to recent PR. Avoid throwing error when status is 204. 
Also included the option to favorite/unfavorite in the table view mode
=> Fix iTwin favorites and add favorites to iTwinGrid table view

common/changes/@itwin/imodel-browser-react/create-new-tag_2024-12-04-18-58.json, packages/apps/storybook/src/imodel-browser/ITwinGrid.stories.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinFavorites.ts
The dropdown was not opening because on first fetch there was no prev links.
=> Fix optional chaining for links in ITwinGrid state management

common/changes/@itwin/imodel-browser-react/itwin-multiple-request_2024-12-05-17-57.json, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.test.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinData.ts, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinFavorites.ts, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinTableConfig.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts, packages/modules/imodel-browser/src/containers/iModelThumbnail/useIModelThumbnail.ts, packages/modules/imodel-browser/src/utils/_apiOverrides.test.ts, packages/modules/imodel-browser/src/utils/_apiOverrides.ts
Refactor ITwinGrid and related hooks to use serverEnvironmentPrefix for API server URL construction
We were using apiOverrides as a dependency for memoization but it was causing the functions to get recalled every time the parent component re-rendered since React checks object using "referential equality". 
Also include a note to memoize accessToken in the iTwinGrid props
=> Avoid unnecessary refetchs

common/changes/@itwin/imodel-browser-react/itwin-grid-doc_2024-12-11-20-54.json, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx
For external packages using this package, specify that accessToken has to be memoized in its function form.
=> Update ITwinGridProps accessToken documentation to specify memoization

common/changes/@itwin/imodel-browser-react/rerender-grid-on-action_2024-12-18-16-51.json, packages/apps/storybook/src/imodel-browser/IModelGrid.stories.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.test.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinTile.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinData.ts, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinTableConfig.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelTableConfig.tsx, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.tsx, packages/modules/imodel-browser/src/utils/_buildMenuOptions.tsx
This PR provides an option for client to refresh the iTwin/iModel list after running an action.
=> Refresh grid on iTwin/iModel action

common/changes/@itwin/imodel-browser-react/nm-acessible-tiles_2025-01-10-00-19.json, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinTile.tsx, packages/modules/imodel-browser/src/containers/iModelThumbnail/IModelThumbnail.tsx
- the imodel/itwin grid tiles were not very accessible
- this is necessary for both accessibility users and e2e testing where these components are used
- aria labels and role=button added for the actionable elements in the tile
- these changes are the *minimum* amount to provide accessibility _not_ the most ideal
- most ideal would be updating to @itwin/itwinui-react 3.x.x + and utilizing [actionable tiles](https://itwinui.bentley.com/docs/tile#actionable) which have native semantic accessibility implementation
https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR35
https://testing-library.com/docs/queries/about/#priority
=> accessibility improved for itwin/imodel grid tiles

common/changes/@itwin/imodel-browser-react/imodel-browser-allow-all-subclasses_2025-01-10-18-23.json, packages/apps/storybook/.env, packages/apps/storybook/src/imodel-browser/ITwinGrid.stories.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinData.ts, packages/modules/imodel-browser/src/types.ts
Adds the option to fetch all iTwins regardless of subclass. This is achieved by using an empty string for the `subClass` query parameter when utilizing the iTwins API. An `All` string literal has been added to the `iTwinSubClass` string literal union to expose this.
=> allow fetching all iTwins regardless of subclass

common/changes/@itwin/imodel-browser-react/fix-skipped-pages_2025-02-05-06-51.json, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelData.ts
The iModel browser was sometimes skipping pages, leading to only showing 100 iModels in an iTwin with 100-200 iModels. 
This was caused by a race condition that I could not reproduce in a test or in the storybook, which is why I did not add a unit test.
I also fixed a warning that the state was being updated in the render phase.
In this screenshot demonstrating the issues, I added some console logs to debug. Notice that the page jumps from 0 to 2.
=> Fix iModel browser skipping pages

common/changes/@itwin/imodel-browser-react/DanishM-description_2025-04-14-08-33.json, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.tsx
Part 1 of [workitem](https://dev.azure.com/bentleycs/iModelTechnologies/_boards/board/t/iTwin%20Studio%20-%20Nebula/Backlog%20items?System.IterationPath=iModelTechnologies%5CiTwin%20Studio%5CNebula%5CMay2025&workitem=1643618)
=> Fixed iModel descriptions missing from iModelGrid

common/changes/@itwin/imodel-browser-react/fix-menu-click_2025-04-17-14-08.json, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelTableConfig.tsx, packages/modules/imodel-browser/src/utils/_buildMenuOptions.tsx
The iTwinUI `MenuItem` was always bubbling the click event, which triggered the table row click event that opens the iModel.
`MenuItem` doesn't expose the real click event, so I wrapped it in a div to intercept it and stop it from bubbling.
=> Fix iModelBrowser menu items in table view always opening iModel

common/changes/@itwin/imodel-browser-react/omar-fix-itwin-search_2025-04-17-16-28.json, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinData.ts
Encoded the search string to account for special characters that end up in the url search
=> iTwin Search box not working with plus sign character

packages/modules/manage-versions/src/clients/namedVersionClient.test.ts, packages/modules/manage-versions/src/clients/namedVersionClient.ts, packages/modules/manage-versions/src/components/ManageVersions/ManageVersions.tsx
Changes: 
1. Updated the query to fetch the named version of the latest changes first.
2. Fixed the infinite scroll issue
Issue: 
1. If there are more than 100 named versions then in first call it is not fetching the named versions of the latest changes.
2. After infinite scroll it only shows the remaining (other than first 100 named version)
=> Fixed the infinite scroll issue on named version page.

common/changes/@itwin/imodel-browser-react/omar-fix-imodel-tile-name_2025-07-10-16-14.json, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.tsx
When using a component for the iModel tile name, the component wouldn't pick up the hover.
Before:
After:
=> Refactor IModelTile component to allow hovering over name label

common/changes/@itwin/imodel-browser-react/omar-fix-imodel-action-opening_2025-07-10-23-24.json, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.tsx
My recent PR broke the iModel actions. Clicking on iModel actions would trigger the onThumbnail click.
=> Fix imodel actions triggering onThumbnail click

common/changes/@itwin/imodel-browser-react/omar-tests-for-imodel-tile_2025-07-11-17-33.json, packages/apps/storybook/src/imodel-browser/IModelTile.stories.tsx, packages/apps/storybook/tsconfig.eslint.json, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.test.tsx, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.tsx
Added tests for the iModel tile as previously suggested in the PR.
=> tests for imodel tile

common/changes/@itwin/imodel-browser-react/omar-cell-overrides-in-imodelgrid_2025-07-12-05-49.json, common/config/rush/pnpm-lock.yaml, packages/apps/storybook/package.json, packages/apps/storybook/src/imodel-browser/IModelGrid.stories.tsx, packages/apps/storybook/src/imodel-browser/ITwinGrid.stories.tsx, packages/modules/imodel-browser/package.json, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.test.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinGrid.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinTile.tsx, packages/modules/imodel-browser/src/containers/ITwinGrid/useITwinTableConfig.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.test.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/IModelGrid.tsx, packages/modules/imodel-browser/src/containers/iModelGrid/useIModelTableConfig.tsx, packages/modules/imodel-browser/src/types.ts
Add ability to provide a custom component for each cell of the iModel/iTwin Grid
Added tests and stories for each.
iTwin Grid
iModel Grid
=> Add cellOverrides option to iModelGrid and iTwinGrid

common/changes/@itwin/imodel-browser-react/show-metadata_2025-07-23-10-05.json, packages/modules/imodel-browser/src/containers/ITwinGrid/ITwinTile.tsx, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.test.tsx, packages/modules/imodel-browser/src/containers/iModelTiles/IModelTile.tsx
This PR fixes a bug, as Tile Metadata was missing even if consumer provided it.
References: [iTwinUI Story](https://itwin.github.io/iTwinUI/react/?source=true&story=tile--all-props&theme=dark#ladle_loc_63)
=> Show Tile Metadata if provided as tileprops

common/changes/@itwin/manage-versions-react/vp-hide-version-feature_2025-06-09-13-26.json, packages/modules/manage-versions/src/clients/namedVersionClient.ts, packages/modules/manage-versions/src/common/configContext.tsx, packages/modules/manage-versions/src/components/ManageVersions/ChangesTab/ChangesTab.tsx, packages/modules/manage-versions/src/components/ManageVersions/ManageVersions.test.tsx, packages/modules/manage-versions/src/components/ManageVersions/ManageVersions.tsx, packages/modules/manage-versions/src/components/ManageVersions/VersionsTab/VersionsTab.scss, packages/modules/manage-versions/src/components/ManageVersions/VersionsTab/VersionsTab.test.tsx, packages/modules/manage-versions/src/components/ManageVersions/VersionsTab/VersionsTab.tsx, packages/modules/manage-versions/src/components/ManageVersions/types.ts, packages/modules/manage-versions/src/mocks.ts, packages/modules/manage-versions/src/models/namedVersion.ts
Changes :-
Hide Version feature:- User can directly hide or unhide an named version from the UI. Initially all the unhidden versions are displayed and after toggle switch user can able to see all the named version. The toggle switch is provided to show hidden versions.
Note :-
enableHideVersions Prop :- This prop is added to manageVersionProps to enable the feature.
The dependency on @types/react-table has been removed according to itwinui V3 Migration.
Show Hidden Version:
Hide Hidden Version:
Disable Hidden Version feature
=> Added hide version option for manage versions with hidden icon
